//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterOfPetAnimalProtectionsManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAccount> tblAccount { get; set; }
        public virtual DbSet<tblPet> tblPet { get; set; }
        public virtual DbSet<tblPetCategory> tblPetCategory { get; set; }
        public virtual DbSet<tblPetDiary> tblPetDiary { get; set; }
        public virtual DbSet<tblPetType> tblPetType { get; set; }
        public virtual DbSet<tblRole> tblRole { get; set; }
    }
}
