//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterOfPetAnimalProtectionsManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPetType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPetType()
        {
            this.tblPet = new HashSet<tblPet>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool status { get; set; }
        public int categoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPet> tblPet { get; set; }
        public virtual tblPetCategory tblPetCategory { get; set; }
    }
}
