//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPet
    {
        public tblPet()
        {
            this.tblPetDiary = new HashSet<tblPetDiary>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string age { get; set; }
        public string furColor { get; set; }
        public Nullable<bool> isSterilized { get; set; }
        public string description { get; set; }
        public bool status { get; set; }
        public System.DateTime createdDate { get; set; }
        public int typeID { get; set; }
        public string adopter { get; set; }
        public Nullable<System.DateTime> dateAdopted { get; set; }
        public string image { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblPetType tblPetType { get; set; }
        public virtual ICollection<tblPetDiary> tblPetDiary { get; set; }
    }
}
