//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPetDiary
    {
        public int id { get; set; }
        public string adopter { get; set; }
        public int petId { get; set; }
        public string diaryDetail { get; set; }
        public string diaryImages { get; set; }
        public System.DateTime createDate { get; set; }
        public bool isRead { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblPet tblPet { get; set; }
    }
}
