//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPetCategory
    {
        public tblPetCategory()
        {
            this.tblPetType = new HashSet<tblPetType>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool status { get; set; }
    
        public virtual ICollection<tblPetType> tblPetType { get; set; }
    }
}
